### ISSUE TITLE
支持这样的bean自动解析吗?

### ISSUE THREAD

**Issue by scaPEGoatno** [pengjianbo/OkHttpFinal#1]
public class Response<T>  {

    /**
     * 状态码 .
     */
    int status;

    /**
     * 信息
     */
    String message;

    /**
     * 结果bean .
     */
    T data;

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public T getData() {
        return data;
    }

    public void setData(T data) {
        this.data = data;
    }

    // 判断结果是否成功
    public boolean isSuccess() {
        return status == 200;
    }

}

**Comment by pengjianbo** [comment]
支持，不过需要业务bean做具体类型说明，请查看demo。

**Comment by scaPEGoatno** [comment]
我想要 里面的 泛型 T data  也 自动 解析 。
json如下
{
  "status" : 200,
  "message" : "查询财富排行榜成功.",
  "data" : {
    "list" : [ {
      "point" : 7.78,
      "timeStr" : "2015-10-04 17:59:29",
      "desc" : "佣金计算4F3E053AC2474411B216CD375964FFB6"
    }, {
      "point" : 1.56,
      "timeStr" : "2015-10-04 17:59:29",
      "desc" : "佣金计算9C6BDAF8DA35465E87533BE41FF653EC"
    }, {
      "point" : 7.78,
      "timeStr" : "2015-10-04 17:59:29",
      "desc" : "佣金计算5353278BF21749999506EB93C8DA57C5"
    }, {
      "point" : 96.23,
      "timeStr" : "2015-10-04 17:59:29",
      "desc" : "佣金计算D97165770D7B48A08194A08C3EBAE95A"
    }, {
      "point" : 24.3,
      "timeStr" : "2015-10-04 17:59:29",
      "desc" : "佣金计算09B7359FB3C34C9DB5108B5E18E5D54A"
    } ]
  }
}
public class Response<T> extends ApiResponse {

/**
 * 状态码 .
 */
int status;

/**
 * 信息
 */
String message;

/**
 * 结果bean .
 */
T data;

public int getStatus() {
    return status;
}

public void setStatus(int status) {
    this.status = status;
}

public String getMessage() {
    return message;
}

public void setMessage(String message) {
    this.message = message;
}

public T getData() {
    return data;
}

public void setData(T data) {
    this.data = data;
}


// 判断结果是否成功
public boolean isSuccess() {
    return status == 200;
}
}

然后 怎样写? 求指教 ...看了 DEMO  还是 有点 迷惑。

**Comment by scaPEGoatno** [comment]
明白了....谢谢 作者  现在项目 开始 使用 这个 库~~~~

**Comment by scaPEGoatno** [comment]
对了 作者 因为 用在 正式项目上      gradle 是最新 版本吗?

**Comment by scaPEGoatno** [comment]
怎样 写 公共的请求 方法?

**Comment by pengjianbo** [comment]
public class BaseApiResponse<T> extends ApiResponse {
    private int status;
    private String message;
    private T data;

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public T getData() {
        return data;
    }

    public void setData(T data) {
        this.data = data;
    }
}

public class RankResponse extends BaseApiResponse<RankResponse.Data> {

    public class Data {
        @SerializedName("list")
        private List<Rank> rankList;

        public List<Rank> getRankList() {
            return rankList;
        }

        public void setRankList(List<Rank> rankList) {
            this.rankList = rankList;
        }

    }

    public class Rank {
        private int point;
        private String timeStr;
        private String desc;

        public int getPoint() {
            return point;
        }

        public void setPoint(int point) {
            this.point = point;
        }

        public String getTimeStr() {
            return timeStr;
        }

        public void setTimeStr(String timeStr) {
            this.timeStr = timeStr;
        }

        public String getDesc() {
            return desc;
        }

        public void setDesc(String desc) {
            this.desc = desc;
        }
    }
}

**Comment by scaPEGoatno** [comment]
是MyBaseHttpRequestCallback吗?
public class BaseApi {

    protected static String BASECLASSPATH = "";




    protected void sendRequest(String url, RequestParams params, final DataCallback callback) {
        BaseHttpRequestCallback<Response> requestCallback = new BaseHttpRequestCallback<Response>() {

            @Override
            public void onSuccess(Response response) {
                if (response.getStatus() == 200) {
                    String json = response.getData().toString();
                    KLog.d("json", json);
                    callback.onSuccess(json);
                }
            }

            @Override
            public void onFailure(int errorCode, String msg) {
                callback.onFailure(msg);
            }
        };

        HttpRequest.post(url, params, requestCallback);
    }



    protected RequestParams getAppParams() {
        RequestParams params = new RequestParams();
        params.put("format", "true");
        String qc_app_str = AppParamEncryptUtil.encryptCharStr();
        String qc_app_sign = AppParamEncryptUtil.signParamStr(qc_app_str, "exy");
        params.put("qc_app_str", qc_app_str);
        params.put("qc_app_sign", qc_app_sign);
        return params;
    }

    protected RequestParams getAppTokenParams() {
        RequestParams params = new RequestParams();
        params.put("format", "true");
        String qc_app_str = AppParamEncryptUtil.encryptCharStr();
        String qc_app_sign = AppParamEncryptUtil.signParamStr(qc_app_str, "exy");
        params.put("qc_app_str", qc_app_str);
        params.put("qc_app_sign", qc_app_sign);
        params.put("qc_app_token", TokenUtil.getToken());
        return params;
    }

}


public class LoginApi extends BaseApi implements ILoginApi {


    @Override
    public void login(String mobile, String password, DataCallback callback) {
        String url = BASECLASSPATH + "";
        RequestParams params = getAppParams();
        params.put("username", mobile);
        params.put("pwd", password);
        sendRequest(url, params, callback);
    }
}

在ui  activity中 是这样请求 
ApiFactory.getInstance().createLoginApi().login(username, password, new DataCallback() {
                @Override
                public void onSuccess(String json) {
                    CommonUI.showToast(context, "登录成功");
                    //  保存到本地SP
//                    LoginBean tokenBean = JSON.parseObject(json, LoginBean.class);
                    LoginBean tokenBean = new Gson().fromJson(json,LoginBean.class);
                    TokenUtil.saveToken(tokenBean.getToken());
                    MainActivity.openThisActivity(LoginActivity.this);
                }

                @Override
                public void onFailure(String message) {
                    CommonUI.showToast(context, message);
                }
            });

就是在baseApi里 想弄个 公共的 请求 方法   泛型 有点 不太熟....

**Comment by pengjianbo** [comment]
LoginBean tokenBean = new Gson().fromJson(json,LoginBean.class);
这个是没必要写，有框架处理，你只需要直接拿到bean使用就行。不需要考虑。
判断你业务成功与失败是在MyBaseHttpRequestCallback中判断，demo中是这样的：
public class MyBaseHttpRequestCallback<T extends BaseApiResponse> extends BaseHttpRequestCallback<T>{

    @Override
    public void onSuccess(T t) {
        int code = t.getCode();
        if ( code == 1 ) {
            super.onSuccess(t);
        } else {
            onLogicFailure(t);
        }
    }
    public void onLogicFailure(T t) {
    }
}

你们的应该是:
public class MyBaseHttpRequestCallback<T extends BaseApiResponse> extends BaseHttpRequestCallback<T>{

    @Override
    public void onSuccess(T t) {
        int status = t.getStatus();
        if ( status == 200 ) {
            super.onSuccess(t);
        } else {
            onLogicFailure(t);
        }
    }
    public void onLogicFailure(T t) {
    }
}

如果还是不明白的地方，可以加我Q：172340021

**Comment by ThreadDeath** [comment]
作者挺耐心的，赞一个，希望项目能维护下去
