### ISSUE TITLE
Post请求如何将参数通过body传入进去

### ISSUE THREAD

**Issue by wl386123298** [pengjianbo/OkHttpFinal#10]
在2.x的okhttp中可以post.body(str)，在okhttpFinal没有找到如何实现这个！

**Comment by pengjianbo** [comment]
可以的。通过ReuestParams setRequestBody方法

**Comment by wl386123298** [comment]
已经搞定，3Q!
RequestParams params = new RequestParams(context);
        params.setCustomRequestBody(RequestBody.create(MediaType.parse("text/plain;charset=utf-8") , str));

**Comment by pengjianbo** [comment]
是的。简单的String用setRequestBody比较好,不需要RequestBody.create

**Comment by wl386123298** [comment]
RequestParams 貌似没有setRequestBody？

**Comment by pengjianbo** [comment]
compile 'cn.finalteam:okhttpfinal:2.0.3'

RequestParams类
```java
public void setCustomRequestBody(RequestBody requestBody) {
        this.requestBody = requestBody;
    }

    public void setRequestBodyString(String string) {
        setRequestBody(MediaType.parse("text/plain; charset=utf-8"), string);
    }

    public void setRequestBody(String mediaType, String string) {
        setRequestBody(MediaType.parse(mediaType), string);
    }

    public void setRequestBody(MediaType mediaType, String string) {
        setCustomRequestBody(RequestBody.create(mediaType, string));
    }
```

重试：
OkHttpFinalConfiguration.Builder类setRetryOnConnectionFailure方法

**Comment by wl386123298** [comment]
求解。为何我这样设置缓存和拦截器代码不执行？
`List<Interceptor> interceptors = new ArrayList<>();
        interceptors.add(new MyHttpInterceptor(getContext()));
        OkHttpFinalConfiguration.Builder builder = new OkHttpFinalConfiguration.Builder()
                .setTimeout(AppConfig.HTTP_REQUEST_TIME_OUT)
                .setHostnameVerifier(new SkirtHttpsHostnameVerifier())
                .setRetryOnConnectionFailure(true)//重试
                .setInterceptors(interceptors)
                .setCache(new Cache(getContext().getCacheDir() , 10 * 1024 * 1024))//设置缓存
                .setDebug(AppConfig.open_debug_log);
        OkHttpFinal.getInstance().init(builder.build());`
