### ISSUE TITLE
求解：偶尔会出现Exception=java.lang.IllegalStateException: closed

### ISSUE THREAD

**Issue by wl386123298** [pengjianbo/OkHttpFinal#11]
E/OkHttpFinal: ║ Thread: AsyncTask #5
E/OkHttpFinal: ║ HttpTask.doInBackground  (HttpTask.java:44)
E/OkHttpFinal: ║    HttpTask.doInBackground  (HttpTask.java:143)
E/OkHttpFinal: ║       ILogger.e  (ILogger.java:82)
E/OkHttpFinal: ║ Exception=java.lang.IllegalStateException: closed

**Comment by pengjianbo** [comment]
请问你使用的是哪个版本？

**Comment by wl386123298** [comment]
最新2.0.4版本！

**Comment by pengjianbo** [comment]
这种情况应该是在DEBUG模式下才会出现吧

**Comment by pengjianbo** [comment]
会不会导致程序奔溃

**Comment by wl386123298** [comment]
不会崩溃，就是请求不到东西，暂时是debug情况下，release暂时还不知道！！！
