### ISSUE TITLE
String httpTaskKey这个参数是干嘛的？还有Demo里为什么RequestParams 不直接用Context

### ISSUE THREAD

**Issue by MIkeeJY** [pengjianbo/OkHttpFinal#13]
public RequestParams(HttpCycleContext cycleContext) {
        this.httpCycleContext = cycleContext;
        init();
    }

**Comment by FanlySff** [comment]
HttpCycleContext 这是一个接口，定义了返回一个网络访问的请求key，httpTaskKey这个参数就代表一个请求key值。如果想要取消一个url访问，底层是通过匹配httpTaskKey取消的。
