### ISSUE TITLE
暂停时java.util.ConcurrentModificationException异常

### ISSUE THREAD

**Issue by weinierfei** [pengjianbo/OkHttpFinal#2]
点击暂停时removeDownloadingMap方法报Iterator遍历异常,

if (TextUtils.equals(key, url)) {
                    try {
                        it.remove();
                    } catch (Exception e) {
                        Logger.e(e);
                    }
                    if (task != null) {
                        task.setInterrupt(true);
                    }
                    break;
                }

这两个方法换一下位置是不是就对了

**Comment by pengjianbo** [comment]
1、是会报ConcurrentModificationException异常，因为下载速度太快了，多线程同时操作集合。不过不会影响功能。在下个新版我会重点优化下载管理。
2、以上代码换个位置也是一样的

**Comment by pengjianbo** [comment]
最近将会提交OkHttpFinal最新版本，将重写下载管理，更新okhttp至3.0。

**Comment by pengjianbo** [comment]
下载管理已迁移到https://github.com/pengjianbo/FileDownloaderFinal 。新库以上问题将不存在。tks
