### ISSUE TITLE
希望添加以Context为标记的请求取消方法

### ISSUE THREAD

**Issue by EricInCD** [pengjianbo/OkHttpFinal#6]
可以参考Android Async Http的请求取消方法。
比较有实用意义。

**Comment by EricInCD** [comment]
或者说加一个Object类型的tag吧。。。

**Comment by pengjianbo** [comment]
现在就支持cancel的,HttpRequest.cancel(url),参数是发起请求是的url（url其实就是tag），请求的时候默认就是把url添加为tag。

**Comment by EricInCD** [comment]
哦哦，这样啊，哈哈~如果能换成Object类型就好啦。
