### ISSUE TITLE
最近爬了下上传文件的东西，你这个很不错啊，但是我觉得上传和下载分开来做两个开源项目会更好，本人做了一个纯文件下载的框架，没用OkHttp，https://github.com/wlfcolin/file-downloader

### ISSUE THREAD

**Issue by wlfcolin** [pengjianbo/OkHttpFinal#9]
最近爬了下上传文件的东西，你这个很不错啊，但是我觉得上传和下载分开来做两个开源项目会更好，本人做了一个纯文件下载的框架，没用OkHttp，https://github.com/wlfcolin/file-downloader

**Comment by pengjianbo** [comment]
你好。下载管理将会在下个版本重写。是基于https://github.com/lingochamp/FileDownloader进行封装的。之后的版本将会OkHttpFinal和OkHttpFinal-DM分离（相互不依赖）。谢谢

**Comment by pengjianbo** [comment]
谢谢你的建议，新库地址为https://github.com/pengjianbo/FileDownloaderFinal
